# 00. PyTorch Fundamentals

Ref : https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


### Tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [6,7,8]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

### Random Tensors
A lot of NNs start with random numbers, then update vals

In [ ]:
randTensor = torch.rand(3,4)
randTensor

tensor([[0.6468, 0.8387, 0.7486, 0.5754],
        [0.9556, 0.6019, 0.4866, 0.8993],
        [0.4137, 0.5091, 0.8271, 0.6588]])

In [ ]:
imageTensor = torch.rand(size=(224, 224, 3)) #(height, width, colour channels(RGB))
imageTensor.shape, imageTensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones (Masks)

In [ ]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*randTensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

###Range of Tensors and Tensor Likes

In [ ]:
rangeTensor = torch.arange(start = 0, end = 100, step = 7)

In [ ]:
rangeTensor.shape

torch.Size([15])

In [ ]:
similarTensor = torch.ones_like(input=rangeTensor)
similarTensor

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor dtypes

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,  #float32 by default
                               device = None, #cpu or cuda
                               requires_grad=False) #tracking gradients

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor-10

tensor([-9, -8, -7])

In [ ]:
tensor*tensor

tensor([1, 4, 9])

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 940 µs, sys: 0 ns, total: 940 µs
Wall time: 2.02 ms


tensor(14)

### For matrix multiplication
The *inner dimensions* must match : (3,2) @ (2,3) <br>
Resulting matrix has the shape of *outer dimensions* : (3,3)

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

In [ ]:
# torch.mm(tensor_A, tensor_B) wrong shapes

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding min, max, mean, sum etc (tensor aggregation)

In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# torch.mean(x) invalid dtype

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
x.type(torch.float32).mean(), torch.mean(x.type(torch.float32))

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
x.argmin(), x.argmax() #min and max value indices

(tensor(0), tensor(9))

## Reshaping, stacking, squeezing and unsqueezing
torch.reshape(input, shape)	-  Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().   
Tensor.view(shape) -  Returns a view of the original tensor in a different shape but shares the same data as the original tensor.  
torch.stack(tensors, dim=0)	-   Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.  
torch.squeeze(input) - Squeezes input to remove all the dimensions with value 1.  
torch.unsqueeze(input, dim) -	  Returns input with a dimension value of 1 added at dim.   
torch.permute(input, dims) -  Returns a view of the original input with its dimensions permuted (rearranged) to dims.  

In [ ]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[:, 0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped, x_reshaped.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_col = torch.rand(size=(244, 244, 3))
x_col.shape

torch.Size([244, 244, 3])

In [ ]:
x_perm = x_col.permute(2,0,1)
x_perm.shape

torch.Size([3, 244, 244])

In [ ]:
x_col[0,0,0] = 100
x_perm[0,0,0]

tensor(100.)

## Indexing

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0], x[0][0], x[0][0][0]


(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [ ]:
x[:, 0] #0th dimension and the 0 index of 1st dimension

(tensor([[1, 2, 3]]), tensor([[2, 5, 8]]))

In [ ]:
x[:, :, 1] #0th and 1st dimension but only index 1 of 2nd dimension

tensor([[2, 5, 8]])

In [ ]:
x[:, 1, 1] #0th dimension but only the 1 index value of the 1st and 2nd dimension

tensor([5])

## From Numpy


In [ ]:
import numpy as np
array = np.arange(1.0, 9.0) #by default float64
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [ ]:
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7., 8.]))

## Reproducibility
NNs
start with random numbers -> tensor operations -> try to make better (again and again and again)  



In [ ]:
tensor_A = torch.rand(3,4)
tensor_B = torch.rand(3,4)

print("Tensor A :\n", tensor_A, "\n\nTensor B :\n", tensor_B, "\n\n")
tensor_A == tensor_B

Tensor A :
 tensor([[0.1158, 0.5829, 0.4800, 0.7637],
        [0.1475, 0.9440, 0.3282, 0.2116],
        [0.9715, 0.4890, 0.4627, 0.4206]]) 

Tensor B :
 tensor([[0.5125, 0.8402, 0.8278, 0.1383],
        [0.2776, 0.5945, 0.5149, 0.8260],
        [0.6572, 0.0859, 0.8640, 0.3381]]) 




tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
import random

RANDOM_SEED=42
torch.manual_seed(seed=RANDOM_SEED)
tensor_C = torch.rand(3,4)

# Have to reset seed everytime new rand() is called for reproducibility
torch.random.manual_seed(seed=RANDOM_SEED)
tensor_D = torch.rand(3,4)

print("Tensor C :\n", tensor_C, "\n\nTensor D :\n", tensor_D, "\n\n")
tensor_C == tensor_D

Tensor C :
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) 

Tensor D :
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) 




tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Tensors on GPUs (fast computations)
Easy to do on Colab but doesn't save your data outputs, limited compute, subject to timeouts  
Difficult and Expensive on Local / Cloud Computers

In [ ]:
!nvidia-smi

Fri Feb 23 14:18:31 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   62C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
torch.cuda.is_available(), torch.cuda.device_count()

(True, 1)

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
tensor = torch.tensor([1., 2., 3.])
print(tensor, tensor.device)

tensor_gpu = tensor.to(device)
tensor_gpu

tensor([1., 2., 3.]) cpu


tensor([1., 2., 3.], device='cuda:0')

In [ ]:
# to get back on cpu, make a copy
tensor_gpu.cpu().numpy()

array([1., 2., 3.], dtype=float32)

In [ ]:
tensor_gpu # still in gpu

tensor([1., 2., 3.], device='cuda:0')